// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List       = require("bs-platform/lib/js/list.js");
var $$Array    = require("bs-platform/lib/js/array.js");
var Curry      = require("bs-platform/lib/js/curry.js");
var $$String   = require("bs-platform/lib/js/string.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function splitString(sep, str) {
  return $$Array.to_list(str.split(sep));
}

function linesOfString(param) {
  return $$Array.to_list(param.split("\n"));
}

function wordsOfString(param) {
  return $$Array.to_list(param.split(" "));
}

function charsOfString(s) {
  return $$Array.to_list(Array.from(s));
}

function stringOfChars(chars) {
  return $$String.concat("", List.map((function (param) {
                    return $$String.make(1, param);
                  }), chars));
}

function zip2(xs, ys) {
  return List.fold_left2((function (list, x, y) {
                return /* :: */[
                        /* tuple */[
                          x,
                          y
                        ],
                        list
                      ];
              }), /* [] */0, xs, ys);
}

function range(until) {
  var makeRange = function (_list, _next) {
    while(true) {
      var next = _next;
      var list = _list;
      var match = +(next > until);
      if (match !== 0) {
        return list;
      } else {
        _next = next + 1 | 0;
        _list = /* :: */[
          next,
          list
        ];
        continue ;
        
      }
    };
  };
  return List.rev(makeRange(/* [] */0, 0));
}

function isSome(param) {
  if (param) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

function expect(str, x) {
  if (x) {
    return x[0];
  } else {
    return Pervasives.failwith(str);
  }
}

function $great$great(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function remember(pred, reference, nextValue) {
  if (Curry._2(pred, nextValue, reference[0])) {
    reference[0] = nextValue;
  }
  return nextValue;
}

exports.splitString   = splitString;
exports.linesOfString = linesOfString;
exports.wordsOfString = wordsOfString;
exports.charsOfString = charsOfString;
exports.stringOfChars = stringOfChars;
exports.zip2          = zip2;
exports.range         = range;
exports.isSome        = isSome;
exports.expect        = expect;
exports.$great$great  = $great$great;
exports.remember      = remember;
/* No side effect */
