// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                = require("bs-platform/lib/js/list.js");
var $$Array             = require("bs-platform/lib/js/array.js");
var Pervasives          = require("bs-platform/lib/js/pervasives.js");
var Inputs$AdventOfCode = require("./Inputs.bs.js");

function directionOfString(str) {
  switch (str) {
    case "n" : 
        return /* N */1;
    case "ne" : 
        return /* NE */2;
    case "nw" : 
        return /* NW */0;
    case "s" : 
        return /* S */4;
    case "se" : 
        return /* SE */5;
    case "sw" : 
        return /* SW */3;
    default:
      return Pervasives.failwith("Unrecognized direction: " + str);
  }
}

function stepsOfString(str) {
  return List.map(directionOfString, $$Array.to_list(str.split(",")));
}

console.log(stepsOfString(Inputs$AdventOfCode.day11));

exports.directionOfString = directionOfString;
exports.stepsOfString     = stepsOfString;
/*  Not a pure module */
